// One-shot generator for JSON fixtures derived from canonical patterns.
// Usage: pnpm tsx scripts/gen-fixtures.ts
// Re-run only when the canonical pattern changes — outputs are checked into git.

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildHistory,
  PATTERN_9MO,
} from '../tests/fixtures/builders.ts';
import type { SleepSession } from '../src/types.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = resolve(__dirname, '../tests/fixtures');

const pad = (n: number): string => String(n).padStart(2, '0');
const toLocalISO = (d: Date): string =>
  `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T` +
  `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;

function serializeHistory(history: SleepSession[]): Array<{ start: string; end: string; type: string }> {
  return history.map((s) => ({
    start: toLocalISO(s.start),
    end: toLocalISO(s.end),
    type: s.type,
  }));
}

// nine-month-old.json — 14 days of canonical 9mo pattern with target wake 07:00.
{
  const history = buildHistory(2026, 4, 27, 14, PATTERN_9MO);
  const fixture = {
    _comment:
      'Scenariusz 2/4 — 9mo (dateOfBirth ≈ 2025-08-27), 14 dni canonical pattern PATTERN_9MO (night 19:30→06:00, naps 09:00 ×63min, 13:30 ×63min). targetWakeTime 07:00. Generated by scripts/gen-fixtures.ts.',
    now: '2026-05-27T15:00:00',
    profile: {
      dateOfBirth: '2025-08-27T00:00:00',
      targetWakeTime: { hour: 7, minute: 0 },
    },
    history: serializeHistory(history),
  };
  const path = resolve(FIXTURE_DIR, 'nine-month-old.json');
  writeFileSync(path, JSON.stringify(fixture, null, 2) + '\n');
  console.log(`wrote ${path} (${fixture.history.length} sessions)`);
}
